# Generated by Django 5.2.3 on 2025-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LumenResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_claim', models.CharField(max_length=255)),
                ('verdict', models.CharField(max_length=31)),
                ('reasoning', models.TextField()),
                ('rating', models.IntegerField()),
                ('web_links', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
